baseURL = "https://syahrulfadli.netlify.app"
languageCode = "en-us"
title = "Syahrul Fadli"
theme = "hugo-theme-novela"

pygmentsstyle = "monokai"

# post pagination
paginate = "6"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45


[outputs]
home = ["HTML", "RSS"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
series = "series"

[social]
github = "#"
