baseURL = "https://www.syahrulfadli.com"
languageCode = "id_ID"
title = "Syahrul Fadli"
theme = "hugo-theme-novela"

# google analytics
googleAnalytics = "UA-86900381-1"

pygmentsstyle = "monokai"

# post pagination
paginate = "6"
# disqus short name
disqusShortname = "jurusanakelektro"

[permalinks]
  post = "/:filename/"

enableRobotsTXT = "true"

[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

[params]
  description = "Blog pribadi yang membahas topik seputar elektronika, komputer dan internet."
  images = ["images/favicon.svg"]
  title = "Syahrul Fadli"

[taxonomies]
tag = "tags"
author = "authors"
series = "series" 

[menu]
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/about/"
    weight = 1
    [[menu.main]]
    identifier = "privasi"
    name = "Privasi"
    url = "/privacy/"
    weight = 2
    [[menu.main]]
    identifier = "penolakan"
    name = "Penolakan"
    url = "/disclaimer/"
    weight = 3
    [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 4
    [[menu.main]]
    identifier = "arsip"
    name = "Arsip"
    url = "/arsip/"
    weight = 4