baseURL = "https://syahrulfadli.netlify.app"
languageCode = "id_ID"
title = "Syahrul Fadli"
theme = "hugo-theme-novela"

pygmentsstyle = "monokai"

# post pagination
paginate = "6"
# disqus short name
disqusShortname = "jurusanakelektro"
# google analytics
googleAnalytics = "UA-86900381-1"


[outputs]
home = ["HTML", "RSS"]

[params]
  description = "Blog pribadi yang membahas topik elektronika dan internet."
  images = ["images/favicon.svg"]
  title = "Syahrul Fadli"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
series = "series"

[social]
github = "#"
