baseURL = "https://syahrulfadli.netlify.app"
languageCode = "id_ID"
title = "Syahrul Fadli"
theme = "hugo-theme-novela"

pygmentsstyle = "monokai"

# post pagination
paginate = "6"
# disqus short name
disqusShortname = "jurusanakelektro"
# google analytics
googleAnalytics = "UA-86900381-1"

[permalinks]
  post = "/:filename/"

[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

[params]
  description = "Blog pribadi yang membahas topik seputar elektronika, komputer dan internet."
  images = ["images/favicon.svg"]
  title = "Syahrul Fadli"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
series = "series" 

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

enableRobotsTXT = "true"

[menu]
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/about/"
    weight = 1
    [[menu.main]]
    identifier = "privasi"
    name = "Privasi"
    url = "/privacy/"
    weight = 4
    [[menu.main]]
    identifier = "penolakan"
    name = "Penolakan"
    url = "/disclaimer/"
    weight = 5
    [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 3