baseURL = "https://fadlii.netlify.app/"
languageCode = "id_ID"
title = "Syahrul Fadli"
theme = "hugo-theme-novela"
timeout = 60000

enableRobotsTXT = true

# google analytics
googleAnalytics = "UA-180573498-1"

# post pagination
paginate = "6"

summarylength = 2

[permalinks]
  post = "/:filename/"


[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

robotsdisallow = false

[module]
  [[module.mounts]]
    source = "./node_modules/bootstrap-icons/font/"
    target = "assets/css"

[params]
  description = "Blog pribadi yang membahas topik seputar elektronika, komputer dan internet."
  images = ["images/favicon.svg"]
  title = "Syahrul Fadli"

[taxonomies]
tag = "tags"
author = "authors"
series = "series" 

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4

[menu]
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang"
    url = "/about/"
    weight = 1
    [[menu.main]]
    identifier = "privasi"
    name = "Privasi"
    url = "/privacy/"
    weight = 2
    [[menu.main]]
    identifier = "penolakan"
    name = "Penolakan"
    url = "/disclaimer/"
    weight = 3
    [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 4
    [[menu.main]]
    identifier = "arsip"
    name = "Arsip"
    url = "/arsip/"
    weight = 4